In [12]:
# Requirement (or) Problem Statement
#===================================
# Salary Prediction based on the years of experience. 

# Customer shared Salary_Data.csv file. From that we are confirming below stages.
# Stage 1 : As both input and output are in numeric, we can choose "Machine Learning(ML)"
# Stage 2 : As both input and output are very clear, we can choose "Supervised Learning"
# Stage 3 : As the output values are in continuous numerical values, we can choose "Regression", 
#           under Regression we are choosing "Simple Linear Algorithm"

In [11]:
# In this note book step by step explanation given for the AI Model Creation by mapping with Model Creation Phases

In [2]:
# First need to load important libraries. 
import pandas as pd

In [5]:
#In the above step we are downloading a global library "pandas" which is useful to handle database related activities.
#as refers renaming/assigning/refering. Here we are refering pandas pd. So whenever we are about to call pandas we use pd. 

In [13]:
#==================================
#****** DATA COLLECTION PHASE *****
#==================================

In [6]:
dataset=pd.read_csv("Salary_Data.csv")

In [7]:
#pd.read_csv is a panda's function used to read the content of the csv file which is provided inside the paranthesis.

In [8]:
#The read value has been stored in the variable called dataset. 
#***   NOTE *** The csv file and ipython notebook should present in the same folder. And also while writing the file name there should not be any error. Else we will get file not found error.

In [9]:
dataset # Displaying the content of the dataset varialbe

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [16]:
# Upon printing the dataset we confirm that the content of the Salary_Data.csv file have been copied successfully in the variable dataset.

In [14]:
#==============================
#***** DATA PREPROCESSING *****
#==============================

In [15]:
# Here we are considering that we have got pre processed data. 
# As DATA PREPROCESSING is a huge topic, we will studying about that in separate session.

In [17]:
#==============================
#***** INPUT/OUTPUT SPLIT *****
#==============================

In [18]:
independent=dataset[["YearsExperience"]]

In [ ]:
#The above code is used to split a single column data of dataset and store into a variable called "independent"

In [19]:
#Here dataset contains the whole data of the "Salary_Data.csv" file. From that to split one column data we are using the above code.

In [20]:
#independent variable holds the data of a single collumn "YearsExperience".
#To store multiple columns data in a single variable can use below syntax.
independents=dataset[["YearsExperience","Salary"]] # example to store multiple columns in a single variable
independents # print the variable.

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [21]:
dependent=dataset[["Salary"]] # Storing output column data in a variable called dependent
dependent #display dependent variable content

Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [22]:
#=======================================================
#***** SPLIT TRAIN AND TEST SET *****
#=======================================================

In [23]:
#sklearn is a another library like panda. 
#sklearn is very much useful to handle ML(Machine Learning)

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
#By using the above code instead of downloading all functionalities of sklearn library, can download only required functionalities. 
#For example here we are downloading only train_test_split functionality from sklearn library.

In [26]:
#**** train_test_split *****
#===========================
#This is parameterized function which contains below four parameters.
#     1.input variable parameter ==> in our case "independent"
#     2.output variable parameter ==> in our case "dependent"
#     3.test set data size parameter ==> we are keeping 30% of provided data(csv file => dataset) for test data. Remaining for train set.
#     4.random_state = 0 ==>> we will study about this in upcoming sessions.

In [35]:
train_test_split(independent, dependent, test_size=0.30, random_state=0)


[    YearsExperience
 22              7.9
 5               2.9
 16              5.1
 8               3.2
 14              4.5
 23              8.2
 20              6.8
 1               1.3
 29             10.5
 6               3.0
 4               2.2
 18              5.9
 19              6.0
 9               3.7
 7               3.2
 25              9.0
 3               2.0
 0               1.1
 21              7.1
 15              4.9
 12              4.0,     YearsExperience
 2               1.5
 28             10.3
 13              4.1
 10              3.9
 26              9.5
 24              8.7
 27              9.6
 11              4.0
 17              5.3,       Salary
 22  101302.0
 5    56642.0
 16   66029.0
 8    64445.0
 14   61111.0
 23  113812.0
 20   91738.0
 1    46205.0
 29  121872.0
 6    60150.0
 4    39891.0
 18   81363.0
 19   93940.0
 9    57189.0
 7    54445.0
 25  105582.0
 3    43525.0
 0    39343.0
 21   98273.0
 15   67938.0
 12   56957.0,       Salary
 2    

In [37]:
#Upon calling the train_test_split function with four parameters, 
#we are getting the four outputs, 2 sets of YearsExperience and 2 sets of Salary
#we need to store all these outputs in respective variables, so that we can use those variables when needed.

#Variables and their usage
#=========================
#    1. X_Train ==> To store train set data of input variable(independent)
#    2. X_Test  ==> To store test set data of input variable(independent)

#    3. Y_Train ==> To store train set data of output variable(dependent)
#    4. Y_Test  ==> To store test set data of output variable(dependent)

X_Train, X_Test, Y_Train, Y_Test=train_test_split(independent,dependent,test_size=0.30,random_state=0) #Splitting Train and Test Set

In [41]:
### Train and Test Set Splitted

#X_Train # Display Train Set of Input Data
#Y_Train # Display Train Set of Output Data


#X_Test # Display Test Set of Input Data
#Y_Test # Display Test Set of Output Data

Salary
22  101302.0
5    56642.0
16   66029.0
8    64445.0
14   61111.0
23  113812.0
20   91738.0
1    46205.0
29  121872.0
6    60150.0
4    39891.0
18   81363.0
19   93940.0
9    57189.0
7    54445.0
25  105582.0
3    43525.0
0    39343.0
21   98273.0
15   67938.0
12   56957.0

In [42]:
#=======================================================
#***** MODEL CREATION (OR) LEARNING PHASE *****
#=======================================================

In [43]:
#We decided that we will be using SLR(Simple Linear Algorithm) for our model creation. 
#For that below code needs to be executed

In [44]:
from sklearn.linear_model import LinearRegression

In [45]:
regressor=LinearRegression() #Assigning the LinearRegression() name along with its functionalities to a varible called regressor for our easy access

In [46]:
#=========================================================================
######################## AI SECRET #######################################
#=========================================================================
#All coding will be same in any domain of AI(ML,DL,NLP,Timeseries Analysis) except the algorithm calling(the above 2 line of code)

In [47]:
regressor.fit(X_Train,Y_Train) # Learning Phase (or) Model Creation

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [48]:
#By using the above code, we are making our brain to learn. Here we are loading the material of both input and output train set.
#Using those material, our model will learning and it is ready for evaluation.
#Model Creation Done means in the algorithm we have successfully calculated the values for the constants.
#For example in the SLR formula: Y = wX+b , upon executing fit method w(weight/slope/ratio) and b(bias/origin/intercept) values are calculated internally.

In [49]:
#By executing below code we can see the calculated values of w and b.

In [53]:
weight = regressor.coef_     #assigning w value into a variable called weight

In [52]:
weight #printing weight variable value

array([[9360.26128619]])

In [54]:
bais = regressor.intercept_ #assigning b value into a variable called bais
bais #printing bais variable value

array([26777.3913412])

In [55]:
#=======================================================
#***** EVALUATION METRICS *****
#=======================================================

In [56]:
#Once learning phase/model creation is done we need to cross verify/evaluate that our model is performance well.
#So to perform the evaluation we have test set data of both input and actual output, 
#we need to find the predicted output set data with the help of input test set data as follows. 

In [57]:
Y_Pred=regressor.predict(X_Test) #By passing input test set data, we are capturing the our AI brain predicted values.
Y_Pred #Print the predicted output test set data

array([[ 40817.78327049],
       [123188.08258899],
       [ 65154.46261459],
       [ 63282.41035735],
       [115699.87356004],
       [108211.66453108],
       [116635.89968866],
       [ 64218.43648597],
       [ 76386.77615802]])

In [58]:
#Now we have Y_Test(Actual Output Test Set Data) and 
#            Y_Pred(Predicted Output Test Set Data)
#By using these variables we can make a war and confirm on our model performance by using below RSquare method.

In [59]:
from sklearn.metrics import r2_score # downloading r2_score evaluation metrics functionality in our file memory

In [60]:
r_score = r2_score(Y_Test,Y_Pred) # Performing the RSquare evaluation by passing actual and predicted test output data and storing the result into a variable called r_score

In [61]:
r_score # printing the value of r_score, if it is nearly 1 then our AI brain is performing well else not.

0.9740993407213511

In [62]:
# As the score is nearly 1, our model is performing well. We can save this best model.

In [63]:
#=======================================================
#***** SAVE THE BEST MODEL *****
#=======================================================

In [64]:
# pickle is a library is used to save the models, so we need to download the pickle library 

In [65]:
import pickle # used to save the models.

In [66]:
filename = "My_First_AI_Model.sav" # creating a empty file called My_First_AI_Model.sav file to save my model, it has been assigned into a variable called filename. 

In [68]:
pickle.dump(regressor,open(filename,'wb')) # upon executing this line a file named "My_First_AI_Modle.sav" is created in the respective folder

In [69]:
#Our overall model functionality has been stored in a varialbe called regressor, now we are saving/writing/dumping 
#the content of variable into a file using the above code.
#Here wb means write binary

In [70]:
#=======================================================
#***** TEST THE MODEL BEFORE DEPLOYMENT *****
#=======================================================

In [71]:
loaded_model=pickle.load(open("My_First_AI_Model.sav",'rb')) 

In [72]:
#Using pickle.load method read the content of our model into a variable "loaded_model"

In [73]:
result=loaded_model.predict([[15]]) # checking for 15 years of experience what is the predicted salary

In [74]:
result

array([[167181.3106341]])

In [75]:
result=loaded_model.predict([[13]]) # checking for 13 years of experience what is the predicted salary

In [76]:
result

array([[148460.78806172]])

In [77]:
result=loaded_model.predict([[0]]) # checking for 0 years of experience what is the predicted salary

In [78]:
result

array([[26777.3913412]])

In [ ]:
#when we pass 0 as input in our model
# Y = wX+c   => w = 9360.26128619 , b = 26777.3913412
# Y = (9360.26128619)X + 26777.3913412 => X = 0 ===> Input
# Y = (9360.26128619)0 + 26777.3913412
# Y = 26777.3913412 ===> Output as same as origin/bias/intercept value when we pass 0 as input.